seller_two backups /seller_two_v6/config/routes.rb
Rails.application.routes.draw do
  scope :authenticate do
    devise_for :users
  end

  resources :users
  resources :revised_two_level_categories
  resources :three_level_categories
  resources :master_category_mappings
  resources :product_three_level_categories
  resources :categories

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#error_404'
  end

  get "/delete-migrations-ask" => "categories#delete_migrations_ask"
  get "/delete-migrations" => "categories#delete_migrations" 
  
  get "/validate" => 'validation#new'
  post "/validate_categories"  => 'validation#validate_categories'
  get "/migrate" => 'migration#new'
  get "/migrate_categories" => 'migration#migrate_categories'

  get "/migration/delete" => 'migration#delete'
  get "/migration_success" => 'migration#success'
  get "/manage" => 'migration#manage'
  root to: 'users#index'

end

seller_two backups /seller_two_v6/app/models/master_category_mapping.rb
class MasterCategoryMapping < ActiveRecord::Base
	establish_connection "admin".to_sym
  attr_accessible :third_level_id,:revised_second_level_id,:current_second_level_id
  
  def self.mapped_categories
     third_level_name = ThreeLevelCategory.select(:name).where(id: self.third_level_id)
     revised_second_level_name = RevisedSecondLevelCategory.select(:name).where(id: self.revised_second_level_id)
     current_second_level_name = CurrentSecondLevel.select(:name).where(id: self.current_second_level_id)
     [third_level_name,revised_second_level_name,current_second_level_name]
  end

  def self.delete_table_rows
    delete_all
  end
end

seller_two backups /seller_two_v6/app/controllers/master_category_mappings_controller.rb
class MasterCategoryMappingsController < ApplicationController
  before_action :set_master_category_mapping, only: [:show, :edit, :update, :destroy]
  layout 'manage'
  # GET /master_category_mappings
  # GET /master_category_mappings.json
  def index
    @master_category_mappings = MasterCategoryMapping.all
  end

  # GET /master_category_mappings/1
  # GET /master_category_mappings/1.json
  def show
  end

  # GET /master_category_mappings/new
  def new
    @master_category_mapping = MasterCategoryMapping.new
  end

  # GET /master_category_mappings/1/edit
  def edit
  end

  # POST /master_category_mappings
  # POST /master_category_mappings.json
  def create
    @master_category_mapping = MasterCategoryMapping.new(master_category_mapping_params)

    respond_to do |format|
      if @master_category_mapping.save
        format.html { redirect_to @master_category_mapping, notice: 'Master category mapping was successfully created.' }
        format.json { render :show, status: :created, location: @master_category_mapping }
      else
        format.html { render :new }
        format.json { render json: @master_category_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /master_category_mappings/1
  # PATCH/PUT /master_category_mappings/1.json
  def update
    respond_to do |format|
      if @master_category_mapping.update(master_category_mapping_params)
        format.html { redirect_to @master_category_mapping, notice: 'Master category mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @master_category_mapping }
      else
        format.html { render :edit }
        format.json { render json: @master_category_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master_category_mappings/1
  # DELETE /master_category_mappings/1.json
  def destroy
    @master_category_mapping.destroy
    respond_to do |format|
      format.html { redirect_to master_category_mappings_url, notice: 'Master category mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master_category_mapping
      @master_category_mapping = MasterCategoryMapping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def master_category_mapping_params
      params[:master_category_mapping]
    end
end

seller_two backups /seller_two_v6/app/helpers/master_category_mappings_helper.rb
module MasterCategoryMappingsHelper
end

seller_two backups /seller_two_v6/app/views/master_category_mappings/_form.html.erb
<%= simple_form_for @master_category_mapping, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :third_level_id %>
  <%= error_span(@master_category_mapping[:third_level_id]) %>
  <%= f.input :revised_second_level_id %>
  <%= error_span(@master_category_mapping[:revised_second_level_id]) %>
  <%= f.input :current_second_level_id %>
  <%= error_span(@master_category_mapping[:current_second_level_id]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                master_category_mappings_path, :class => 'btn btn-default' %>
<% end %>

seller_two backups /seller_two_v6/app/views/master_category_mappings/edit.html.erb
<%- model_class = MasterCategoryMapping -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

seller_two backups /seller_two_v6/app/views/master_category_mappings/index.html.erb
<%- model_class = MasterCategoryMapping -%>
    <div class="page-header">
        <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
        <%= link_to t('.new', :default => t("helpers.links.new")),
            new_master_category_mapping_path,
            :class => 'btn btn-primary' %>
        </h1>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    <%= model_class.human_attribute_name(:id) %>
                </th>
                <th>
                    <%= model_class.human_attribute_name(:third_level_id) %>
                </th>
                <th>
                    <%= model_class.human_attribute_name(:revised_second_level_id) %>
                </th>
                <th>
                    <%= model_class.human_attribute_name(:current_second_level_id) %>
                </th>
                <th>
                    <%= model_class.human_attribute_name(:created_at) %>
                </th>
                <th>
                    <%=t '.actions', :default => t("helpers.actions") %>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @master_category_mappings.each do |master_category_mapping| %>
                <tr>
                    <td>
                        <%= link_to master_category_mapping.id, master_category_mapping_path(master_category_mapping) %>
                    </td>
                    <td>
                        <%= master_category_mapping.third_level_id %>
                    </td>
                    <td>
                        <%= master_category_mapping.revised_second_level_id %>
                    </td>
                    <td>
                        <%= master_category_mapping.current_second_level_id %>
                    </td>
                    <td>
                        <%=l master_category_mapping.created_at %>
                    </td>
                    <td>
                        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_master_category_mapping_path(master_category_mapping), :class => 'btn btn-default btn-xs' %>
                            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      master_category_mapping_path(master_category_mapping),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
                    </td>
                </tr>
                <% end %>
        </tbody>
    </table>

seller_two backups /seller_two_v6/app/views/master_category_mappings/new.html.erb
<%- model_class = MasterCategoryMapping -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

seller_two backups /seller_two_v6/app/views/master_category_mappings/show.html.erb
<%- model_class = MasterCategoryMapping -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:third_level_id) %>:</strong></dt>
  <dd><%= @master_category_mapping.third_level_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:revised_second_level_id) %>:</strong></dt>
  <dd><%= @master_category_mapping.revised_second_level_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_second_level_id) %>:</strong></dt>
  <dd><%= @master_category_mapping.current_second_level_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              master_category_mappings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_master_category_mapping_path(@master_category_mapping), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              master_category_mapping_path(@master_category_mapping),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>