seller_two backups /seller_two_v6/config/routes.rb
Rails.application.routes.draw do
  scope :authenticate do
    devise_for :users
  end

  resources :users
  resources :revised_two_level_categories
  resources :three_level_categories
  resources :master_category_mappings
  resources :product_three_level_categories
  resources :categories

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#error_404'
  end

  get "/delete-migrations-ask" => "categories#delete_migrations_ask"
  get "/delete-migrations" => "categories#delete_migrations" 
  
  get "/validate" => 'validation#new'
  post "/validate_categories"  => 'validation#validate_categories'
  get "/migrate" => 'migration#new'
  get "/migrate_categories" => 'migration#migrate_categories'

  get "/migration/delete" => 'migration#delete'
  get "/migration_success" => 'migration#success'
  get "/manage" => 'migration#manage'
  root to: 'users#index'

end

seller_two backups /seller_two_v6/app/models/revised_two_level_category.rb
class RevisedTwoLevelCategory < ActiveRecord::Base
  establish_connection "admin".to_sym
  enum level: [ '0' , '1' ]
  attr_accessible :name , :parent_id , :level

  def children_names
   	 if ["0"].include?(self.level)
   	 ThreeLevelCategory.where(level: self.level.to_i + 1,parent_id: self.id).map &:name
   	else
   		"Not level 0 or 1"
   	end
   end

  def self.delete_table_rows
    delete_all
  end
end

seller_two backups /seller_two_v6/app/controllers/revised_two_level_categories_controller.rb
class RevisedTwoLevelCategoriesController < ApplicationController
  before_action :set_revised_two_level_category, only: [:show, :edit, :update, :destroy]
  
  layout 'manage'
  
  # GET /revised_two_level_categories
  # GET /revised_two_level_categories.json
  def index
    @revised_two_level_categories = RevisedTwoLevelCategory.all
  end

  # GET /revised_two_level_categories/1
  # GET /revised_two_level_categories/1.json
  def show
  end

  # GET /revised_two_level_categories/new
  def new
    @revised_two_level_category = RevisedTwoLevelCategory.new
  end

  # GET /revised_two_level_categories/1/edit
  def edit
  end

  # POST /revised_two_level_categories
  # POST /revised_two_level_categories.json
  def create
    @revised_two_level_category = RevisedTwoLevelCategory.new(revised_two_level_category_params)

    respond_to do |format|
      if @revised_two_level_category.save
        format.html { redirect_to @revised_two_level_category, notice: 'Revised two level category was successfully created.' }
        format.json { render :show, status: :created, location: @revised_two_level_category }
      else
        format.html { render :new }
        format.json { render json: @revised_two_level_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /revised_two_level_categories/1
  # PATCH/PUT /revised_two_level_categories/1.json
  def update
    respond_to do |format|
      if @revised_two_level_category.update(revised_two_level_category_params)
        format.html { redirect_to @revised_two_level_category, notice: 'Revised two level category was successfully updated.' }
        format.json { render :show, status: :ok, location: @revised_two_level_category }
      else
        format.html { render :edit }
        format.json { render json: @revised_two_level_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revised_two_level_categories/1
  # DELETE /revised_two_level_categories/1.json
  def destroy
    @revised_two_level_category.destroy
    respond_to do |format|
      format.html { redirect_to revised_two_level_categories_url, notice: 'Revised two level category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_revised_two_level_category
      @revised_two_level_category = RevisedTwoLevelCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def revised_two_level_category_params
      params[:revised_two_level_category]
    end
end

seller_two backups /seller_two_v6/app/helpers/revised_two_level_categories_helper.rb
module RevisedTwoLevelCategoriesHelper
end

seller_two backups /seller_two_v6/app/views/revised_two_level_categories/_form.html.erb
<%= simple_form_for @revised_two_level_category, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@revised_two_level_category[:name]) %>
  <%= f.input :parent_id %>
  <%= error_span(@revised_two_level_category[:parent_id]) %>
  <%= f.input :level %>
  <%= error_span(@revised_two_level_category[:level]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                revised_two_level_categories_path, :class => 'btn btn-default' %>
<% end %>

seller_two backups /seller_two_v6/app/views/revised_two_level_categories/edit.html.erb
<%- model_class = RevisedTwoLevelCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

seller_two backups /seller_two_v6/app/views/revised_two_level_categories/index.html.erb
<%- model_class = RevisedTwoLevelCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
   <%= link_to t('.new', :default => t("helpers.links.new")),
            new_revised_two_level_category_path,
            :class => 'btn btn-primary' %>
   </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:parent_id) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @revised_two_level_categories.each do |revised_two_level_category| %>
      <tr>
        <td><%= link_to revised_two_level_category.id, revised_two_level_category_path(revised_two_level_category) %></td>
        <td><%= revised_two_level_category.name %></td>
        <td><%= revised_two_level_category.parent_id %></td>
        <td><%= revised_two_level_category.level %></td>
        <td><%=l revised_two_level_category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_revised_two_level_category_path(revised_two_level_category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      revised_two_level_category_path(revised_two_level_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

seller_two backups /seller_two_v6/app/views/revised_two_level_categories/new.html.erb
<%- model_class = RevisedTwoLevelCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

seller_two backups /seller_two_v6/app/views/revised_two_level_categories/show.html.erb
<%- model_class = RevisedTwoLevelCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @revised_two_level_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parent_id) %>:</strong></dt>
  <dd><%= @revised_two_level_category.parent_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @revised_two_level_category.level %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              revised_two_level_categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_revised_two_level_category_path(@revised_two_level_category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              revised_two_level_category_path(@revised_two_level_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>